### ISSUE TITLE
Please change documentation from 'bridge' to 'under'

### ISSUE THREAD

**Issue by lindleyw** [benvanstaveren/Mojolicious-Plugin-Authentication#10]
Since 2015-01-14, Mojolicious::Routes::Route::bridge is deprecated in favor of Mojolicious::Routes::Route::under.

ref:   https://github.com/kraih/mojo/blob/470160814f15505cba1eb6322383e8e7c8574a4f/Changes#L3

**Comment by benvanstaveren** [comment]
Documentation has been updated, new release coming!
