### ISSUE TITLE
Deep recursion at logout subroutine

### ISSUE THREAD

**Issue by pavelsr** [benvanstaveren/Mojolicious-Plugin-Authentication#20]
Hi all,

I have a strange problem.

When I press logout link at my project computer is hanging and I have following at morbo log:

```
Deep recursion on subroutine "MongoPA::Controller::Auth::logout"
```

This is my logout function of MongoPA::Controller::Auth module:

``` perl
sub logout {
    my $self = shift;
    $self->logout;
    $self->redirect_to('/login');
  }
```

And this is related string from a route and template:

``` perl
 $r->get('/logout')->to('auth#logout');
```

``` perl
<a href='<%= url_for("logout") %>'>logout</a>
```

Is it a bug or I made something wrong?

I checked the [code](https://metacpan.org/source/MADCAT/Mojolicious-Plugin-Authentication-1.29/lib/Mojolicious/Plugin/Authentication.pm#L117) of logout method and I haven't found anything that can make such deep recursion error. So I'm a little bit stuck now.

**Comment by benvanstaveren** [comment]
Hi Pavel,

$self->logout will recurse - you have a sub 'logout' defined, and the
actual 'logout' from my module is just a helper, so it'll recurse :)

If you do this, it'll work:

sub do_logout {
  my $self = shift;
  $self->logout;
  $self->redirect_to('/login');
}

And then refer to it with 'do_logout' in your routes :)

**Comment by paulserikov** [comment]
Hi Ben,

Got it, thanks a lot. I just forgot that helpers and custom controller's methods have same namespace. 
Will close this issue.

P.S. However I think that we should figure out in [documentation](https://metacpan.org/pod/Mojolicious::Plugin::Authentication#logout) that to avoid recursion you shouldn't name your controller method as 'logout' :)

**Comment by benvanstaveren** [comment]
Yeah, that's a good point - I'm in the process of a rather significant
rewrite, so I'll see if I can do something documentation/helper wise.
