### ISSUE TITLE
validate_user callback called regardless of auto_validate

### ISSUE THREAD

**Issue by jjatria** [benvanstaveren/Mojolicious-Plugin-Authentication#23]
The documentation states that

> If the extra data hash contains a key `auto_validate`, the value of that key will be used as the UID, and `authenticate` will not call your `validate_user` callback

But [the code in `authenticate`](https://github.com/benvanstaveren/Mojolicious-Plugin-Authentication/blob/15f7f7367df0b0d9c04ee483f0e8602ab1dd7792/lib/Mojolicious/Plugin/Authentication.pm#L122-L143) calls the `validate_user` callback regardless, and ignores its result value if `auto_validate` is present.

If this is by design, then the documentation should be corrected. Otherwise, the code in `authenticate` can be simplified.

**Comment by gypark** [comment]
Hello,

Today I'd found this problem and came here to write about it, but jjatria did it earlier 👍 

I hope new version of this great module be released soon.
