### ISSUE TITLE
broken link in metacpan

### ISSUE THREAD

**Issue by niceperl** [benvanstaveren/Mojolicious-Plugin-Authentication#28]
The [metacpan page](https://metacpan.org/pod/Mojolicious::Plugin::Authentication) of this distro has a broken link at the "issues" section: 

https://gitlab.com/benvanstaveren/Mojolicious-Plugin-Authentication/issues

**Comment by Tekki** [comment]
This would be solved by accepting pull request #26 by @fschlich.

**Comment by benvanstaveren** [comment]
Hi folks,

Excuse my extreme tardiness in responding to issues, I've been having little to no free time to work on this module, so I'll get around to doing it this weekend.

**Comment by jjatria** [comment]
Fixed by merging #26
